project:
  type: website

website:
  title: "ARP1047 filtro de audio e computador analógico"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: bibliografia.qmd
        text: bibliografia

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
