project:
  type: website

website:
  title: "Computador analógico para aplicação em áudio"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: bibliografia.qmd
        text: bibliografia
      - href: intro.qmd
        text: introdução
      - href: materiais-e-metodos.qmd
        text: métodos
      - href: resultados.qmd
        text: resultados
      - href: cronograma
        text: cronograma
  repo-url: https://github.com/gilfuser/computador-analogico-para-aplicacao-em-audio-arp1047
  repo-actions: [edit, source, issue]

  reader-mode: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
